{"uuid": "c2ddcd50-2484-455d-8be2-858f823037dc", "children": ["9bc8f009-c8e3-45e2-abe8-5649b3419e80", "ab940a51-c44a-4ab2-bfd6-2d2823fa2d18", "218b97cf-1e2f-4363-b072-334543e6d644", "691dd0af-f819-48d3-ac40-758754b792ba"], "befores": [{"name": "xunit_setup_class_fixture_TestUserLogin", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_user_data.xlsx'\n", "trace": "  File \"C:\\soft\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\testcase_API\\test_ydy\\test_login.py\", line 18, in setup_class\n    self.data_list = excel_to_list(\"test_user_data.xlsx\", \"TestUserLogin\")\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\lib\\read_excel.py\", line 6, in excel_to_list\n    wb = xlrd.open_workbook(data_file)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\xlrd\\__init__.py\", line 111, in open_workbook\n    with open(filename, \"rb\") as f:\n"}, "start": 1615975176426, "stop": 1615975176426}], "start": 1615975176426, "stop": 1615975176834}