{"uuid": "571c9a1a-43fc-4fde-ae3b-54db96c3be4f", "children": ["182408bb-5003-4a96-8997-5987cf609445", "90917d38-9dcd-48df-adb4-cd5214265eb5", "35f4edbb-a333-4efb-a2c9-deaf9c79f130", "419f2719-347a-4635-9957-dec268b0c793"], "befores": [{"name": "xunit_setup_class_fixture_TestUserLogin", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/test_user_data.xlsx'\n", "trace": "  File \"C:\\soft\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\testcase_API\\test_ydy\\test_login.py\", line 18, in setup_class\n    self.data_list = excel_to_list(\"./data/test_user_data.xlsx\", \"TestUserLogin\")\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\lib\\read_excel.py\", line 6, in excel_to_list\n    wb = xlrd.open_workbook(data_file)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\xlrd\\__init__.py\", line 111, in open_workbook\n    with open(filename, \"rb\") as f:\n"}, "start": 1615975428578, "stop": 1615975428578}], "start": 1615975428578, "stop": 1615975428895}