{"uuid": "a0b4636f-4db6-44ba-8c0f-42d427c85e54", "children": ["d17763c3-3d46-43f9-8c67-7ab7c427dee1", "c9cabe3e-f3da-441f-85d6-6f914d4372d6", "ccbab284-9e1d-4f57-9277-03d8dfd3c203", "038af315-a33d-4da7-8e66-d76e6e236d02"], "befores": [{"name": "xunit_setup_class_fixture_TestUserLogin", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'data\\test_user_data.xlsx'\n", "trace": "  File \"C:\\soft\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\testcase_API\\test_ydy\\test_login.py\", line 18, in setup_class\n    self.data_list = excel_to_list(\"data\\test_user_data.xlsx\", \"TestUserLogin\")\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\lib\\read_excel.py\", line 6, in excel_to_list\n    wb = xlrd.open_workbook(data_file)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\xlrd\\__init__.py\", line 111, in open_workbook\n    with open(filename, \"rb\") as f:\n"}, "start": 1615975355216, "stop": 1615975355216}], "start": 1615975355216, "stop": 1615975355512}